#!/usr/bin/env python3
"""Structural upgrade layer for the yen-carry composite Telegram alert.

Adds three slow-moving signals that should not be confused with an active unwind:
1) JGB 10Y 3% structural/fiscal boundary and consecutive official closes above it.
2) Japan MOF outward flows split into equities vs long-term debt, including 2-week and YTD totals.
3) Latest 10Y/30Y JGB auction quality (bid-to-cover and yield tail) versus the prior auction.

The layer can append context to an alert already generated by yen_carry_composite_watch.
After the initial baseline, it can also create a composite alert when a material structural
state changes. It never turns JGB 10Y 3% alone into an unwind signal.
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import html
import io
import json
import math
import pathlib
import re
import urllib.parse
from dataclasses import asdict, dataclass
from html.parser import HTMLParser
from zoneinfo import ZoneInfo

import global_rates_watch as rates
from khs_source_fetch import fetch_text, record_source_failure

KST = ZoneInfo("Asia/Seoul")
UTC = dt.timezone.utc
ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = ROOT / "out"
DATA.mkdir(exist_ok=True)
OUT.mkdir(exist_ok=True)

STATE_PATH = DATA / "yen_carry_structural_state.json"
PENDING_PATH = OUT / "yen_carry_structural_pending_state.json"
CONTEXT_JSON_PATH = OUT / "yen_carry_structural_context.json"
CONTEXT_MD_PATH = OUT / "yen_carry_structural_context.md"
ALERT_TITLE_PATH = OUT / "yen_carry_composite_alert_title.txt"
ALERT_BODY_PATH = OUT / "yen_carry_composite_alert.md"
ALERT_JSON_PATH = OUT / "yen_carry_composite_alert.json"
COMPOSITE_PENDING_PATH = OUT / "yen_carry_composite_pending_state.json"
CONFIRM_PATH = OUT / "yen_carry_composite_telegram_confirmed.json"

MOF_WEEK_CSV = "https://www.mof.go.jp/policy/international_policy/reference/itn_transactions_in_securities/week.csv"
JGB_WHATS_NEW = "https://www.mof.go.jp/english/public_relations/whats_new/{year}jgbs.html"
USER_AGENT = "Mozilla/5.0 khs-yen-carry-structural/1.0"
JGB10_BOUNDARY = 3.0


@dataclass(frozen=True)
class MofFlowSplit:
    latest_week: str
    previous_week: str
    latest_equity_net_trillion_yen: float
    latest_lt_debt_net_trillion_yen: float
    latest_short_debt_net_trillion_yen: float
    latest_2w_equity_trillion_yen: float
    prior_2w_equity_trillion_yen: float
    latest_2w_lt_debt_trillion_yen: float
    prior_2w_lt_debt_trillion_yen: float
    ytd_equity_trillion_yen: float
    ytd_lt_debt_trillion_yen: float


@dataclass(frozen=True)
class AuctionResult:
    tenor: int
    auction_date: str
    url: str
    competitive_bids_billion_yen: float
    accepted_bids_billion_yen: float
    bid_to_cover: float
    highest_yield_pct: float
    average_yield_pct: float
    tail_bp: float


class AnchorParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.current_href: str | None = None
        self.current_text: list[str] = []
        self.anchors: list[tuple[str, str]] = []

    def handle_starttag(self, tag, attrs):
        if tag.lower() == "a":
            self.current_href = dict(attrs).get("href")
            self.current_text = []

    def handle_data(self, data):
        if self.current_href is not None:
            self.current_text.append(data)

    def handle_endtag(self, tag):
        if tag.lower() == "a" and self.current_href is not None:
            text = " ".join(" ".join(self.current_text).split())
            self.anchors.append((text, self.current_href))
            self.current_href = None
            self.current_text = []


class TableParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.rows: list[list[str]] = []
        self.row: list[str] | None = None
        self.cell: list[str] | None = None

    def handle_starttag(self, tag, attrs):
        t = tag.lower()
        if t == "tr":
            self.row = []
        elif t in {"td", "th"} and self.row is not None:
            self.cell = []

    def handle_data(self, data):
        if self.cell is not None:
            self.cell.append(data)

    def handle_endtag(self, tag):
        t = tag.lower()
        if t in {"td", "th"} and self.cell is not None and self.row is not None:
            self.row.append(" ".join(" ".join(self.cell).split()))
            self.cell = None
        elif t == "tr" and self.row is not None:
            if self.row:
                self.rows.append(self.row)
            self.row = None


def number(value) -> float | None:
    text = str(value or "").replace(",", "").replace("%", "").strip()
    try:
        out = float(text)
    except ValueError:
        return None
    return out if math.isfinite(out) else None


def load_json(path: pathlib.Path, default):
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, type(default)) else default
    except Exception:
        return default


def write_json(path: pathlib.Path, value: dict) -> None:
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def source_failure(name: str, url: str, error: str, now: dt.datetime) -> None:
    record_source_failure(
        lane="yen_carry_structural",
        source_name=name,
        source_url=url,
        error=error,
        checked_at=now.astimezone(KST),
    )


def label_year(label: str) -> int | None:
    match = re.search(r"(20\d{2})", label)
    if match:
        return int(match.group(1))
    match = re.search(r"令和\s*(\d+)\s*年", label)
    if match:
        return 2018 + int(match.group(1))
    return None


def parse_mof_week_split(text: str) -> MofFlowSplit:
    """Split MOF outward flows.

    Official weekly CSV columns after the date label are:
    equity acquisition/disposition/net, long-term debt acquisition/disposition/net,
    subtotal net, short-term debt acquisition/disposition/net, total net.
    Units are 100 million yen; positive net means net acquisition.
    """
    rows: list[dict] = []
    for row in csv.reader(io.StringIO(text.lstrip("\ufeff"))):
        if len(row) < 12:
            continue
        label = (row[0] or "").strip()
        eq = number(row[3])
        lt = number(row[6])
        subtotal = number(row[7])
        st = number(row[10])
        total = number(row[11])
        if not label or None in {eq, lt, subtotal, st, total}:
            continue
        if not any(ch.isdigit() for ch in label):
            continue
        rows.append({"label": label, "year": label_year(label), "eq": eq, "lt": lt, "st": st})
    if len(rows) < 4:
        raise RuntimeError(f"MOF weekly CSV needs >=4 complete outward rows, got {len(rows)}")

    latest4 = rows[-4:]
    prior2, latest2 = latest4[:2], latest4[2:]
    latest_year = rows[-1]["year"]
    year_rows = [r for r in rows if latest_year is not None and r["year"] == latest_year]
    if not year_rows:
        year_rows = rows

    conv = 10000.0  # 100 million yen -> trillion yen
    return MofFlowSplit(
        latest_week=latest2[-1]["label"],
        previous_week=latest2[-2]["label"],
        latest_equity_net_trillion_yen=latest2[-1]["eq"] / conv,
        latest_lt_debt_net_trillion_yen=latest2[-1]["lt"] / conv,
        latest_short_debt_net_trillion_yen=latest2[-1]["st"] / conv,
        latest_2w_equity_trillion_yen=sum(r["eq"] for r in latest2) / conv,
        prior_2w_equity_trillion_yen=sum(r["eq"] for r in prior2) / conv,
        latest_2w_lt_debt_trillion_yen=sum(r["lt"] for r in latest2) / conv,
        prior_2w_lt_debt_trillion_yen=sum(r["lt"] for r in prior2) / conv,
        ytd_equity_trillion_yen=sum(r["eq"] for r in year_rows) / conv,
        ytd_lt_debt_trillion_yen=sum(r["lt"] for r in year_rows) / conv,
    )


def fetch_mof_split(now: dt.datetime) -> MofFlowSplit:
    text, error = fetch_text(MOF_WEEK_CSV, USER_AGENT, timeout=20, attempts=2, accept="text/csv,text/plain,*/*")
    if error or not text:
        raise RuntimeError(error or "empty MOF weekly CSV")
    return parse_mof_week_split(text)


def fetch_jgb10_history() -> list[tuple[str, float]]:
    text, error = fetch_text(rates.JGB_URL, USER_AGENT, timeout=20, attempts=2, accept="text/csv,text/plain,*/*")
    if error or not text:
        raise RuntimeError(error or "empty Japan MOF JGB CSV")
    rows = list(csv.reader(io.StringIO(text.lstrip("\ufeff"))))
    header_idx = None
    for i, row in enumerate(rows[:10]):
        if row and any(re.sub(r"[^a-z0-9]", "", c.lower()) == "date" for c in row):
            header_idx = i
            break
    if header_idx is None:
        raise RuntimeError("JGB CSV header not found")
    header = [re.sub(r"[^a-z0-9]", "", c.lower()) for c in rows[header_idx]]
    date_i = header.index("date")
    candidates = {"10y", "10year", "10"}
    ten_i = next((i for i, key in enumerate(header) if key in candidates), None)
    if ten_i is None:
        raise RuntimeError("JGB CSV 10Y column not found")
    out: list[tuple[str, float]] = []
    for row in rows[header_idx + 1:]:
        if len(row) <= max(date_i, ten_i):
            continue
        value = number(row[ten_i])
        if value is not None and row[date_i].strip():
            out.append((row[date_i].strip(), value))
    if not out:
        raise RuntimeError("JGB CSV 10Y history empty")
    return out


def consecutive_above(rows: list[tuple[str, float]], level: float) -> int:
    count = 0
    for _date, value in reversed(rows):
        if value >= level:
            count += 1
        else:
            break
    return count


def latest_auction_links(year: int, tenor: int) -> list[str]:
    index_url = JGB_WHATS_NEW.format(year=year)
    text, error = fetch_text(index_url, USER_AGENT, timeout=20, attempts=2, accept="text/html,*/*")
    if error or not text:
        raise RuntimeError(error or "empty JGB What's New page")
    parser = AnchorParser()
    parser.feed(text)
    wanted = f"auction result of {tenor}-year jgbs on"
    links: list[str] = []
    for anchor_text, href in parser.anchors:
        low = anchor_text.lower()
        if wanted in low and "market special participants" not in low:
            links.append(urllib.parse.urljoin(index_url, href))
    # Newest entries appear first on MOF What's New.
    return list(dict.fromkeys(links))


def parse_auction_html(text: str, url: str, tenor: int) -> AuctionResult:
    parser = TableParser()
    parser.feed(html.unescape(text))
    target = f"{tenor}-Year".lower()
    row = next((r for r in parser.rows if r and r[0].strip().lower() == target), None)
    if row is None or len(row) < 13:
        raise RuntimeError(f"{tenor}Y auction result row not found")
    bids = number(row[6])
    accepted = number(row[7])
    highest = number(row[9])
    average = number(row[12])
    if None in {bids, accepted, highest, average} or not accepted:
        raise RuntimeError(f"{tenor}Y auction numeric fields incomplete")
    return AuctionResult(
        tenor=tenor,
        auction_date=row[2],
        url=url,
        competitive_bids_billion_yen=float(bids),
        accepted_bids_billion_yen=float(accepted),
        bid_to_cover=float(bids) / float(accepted),
        highest_yield_pct=float(highest),
        average_yield_pct=float(average),
        tail_bp=(float(highest) - float(average)) * 100.0,
    )


def fetch_auction_pair(now: dt.datetime, tenor: int) -> tuple[AuctionResult, AuctionResult | None]:
    links = latest_auction_links(now.astimezone(KST).year, tenor)
    if not links:
        raise RuntimeError(f"latest {tenor}Y auction link not found")
    results: list[AuctionResult] = []
    for url in links[:2]:
        text, error = fetch_text(url, USER_AGENT, timeout=20, attempts=2, accept="text/html,*/*")
        if error or not text:
            continue
        try:
            results.append(parse_auction_html(text, url, tenor))
        except Exception:
            continue
    if not results:
        raise RuntimeError(f"latest {tenor}Y auction result unavailable")
    return results[0], results[1] if len(results) > 1 else None


def auction_label(current: AuctionResult, previous: AuctionResult | None) -> str:
    if previous is None:
        return "직전 비교자료 부족"
    btc_change = current.bid_to_cover - previous.bid_to_cover
    tail_change = current.tail_bp - previous.tail_bp
    if btc_change >= 0.20 and tail_change <= -1.0:
        return "수요 개선"
    if btc_change <= -0.20 and tail_change >= 1.0:
        return "수요 악화"
    return "혼조·대체로 안정"


def is_weak_auction(result: AuctionResult) -> bool:
    return result.bid_to_cover < 2.5 and result.tail_bp >= 5.0


def sign_bucket(value: float | None) -> int:
    if value is None or abs(value) < 1e-12:
        return 0
    return 1 if value > 0 else -1


def make_state(now: dt.datetime, jgb_rows, mof, a10, a30) -> dict:
    latest_date, latest_jgb10 = jgb_rows[-1]
    days = consecutive_above(jgb_rows, JGB10_BOUNDARY)
    return {
        "initialized": True,
        "updated_at_kst": now.astimezone(KST).isoformat(timespec="seconds"),
        "source_dates": {
            "jgb10": latest_date,
            "mof_week": mof.latest_week if mof else None,
            "auction10": a10.auction_date if a10 else None,
            "auction30": a30.auction_date if a30 else None,
        },
        "values": {
            "jgb10": latest_jgb10,
            "jgb10_consecutive_days_ge_3": days,
            "jgb10_ge_3": latest_jgb10 >= JGB10_BOUNDARY,
            "mof_equity_2w_trillion_yen": mof.latest_2w_equity_trillion_yen if mof else None,
            "mof_lt_debt_2w_trillion_yen": mof.latest_2w_lt_debt_trillion_yen if mof else None,
            "mof_lt_debt_ytd_trillion_yen": mof.ytd_lt_debt_trillion_yen if mof else None,
            "auction10_bid_to_cover": a10.bid_to_cover if a10 else None,
            "auction10_tail_bp": a10.tail_bp if a10 else None,
            "auction30_bid_to_cover": a30.bid_to_cover if a30 else None,
            "auction30_tail_bp": a30.tail_bp if a30 else None,
        },
    }


def structural_reasons(previous: dict, pending: dict, risk_active: bool) -> list[str]:
    if not previous.get("initialized"):
        return []
    reasons: list[str] = []
    oldv, newv = previous.get("values") or {}, pending.get("values") or {}
    olds, news = previous.get("source_dates") or {}, pending.get("source_dates") or {}

    old_above, new_above = bool(oldv.get("jgb10_ge_3")), bool(newv.get("jgb10_ge_3"))
    if old_above != new_above:
        reasons.append("JGB 10년 3% 구조적 경계 진입" if new_above else "JGB 10년 3% 구조적 경계 재하락")

    old_persist = int(oldv.get("jgb10_consecutive_days_ge_3") or 0) >= 2
    new_persist = int(newv.get("jgb10_consecutive_days_ge_3") or 0) >= 2
    if old_persist != new_persist:
        reasons.append("JGB 10년 3% 이상 2영업일 지속 확인" if new_persist else "JGB 10년 3% 이상 지속 상태 해제")

    if olds.get("mof_week") and news.get("mof_week") and olds.get("mof_week") != news.get("mof_week"):
        old_2w = number(oldv.get("mof_lt_debt_2w_trillion_yen"))
        new_2w = number(newv.get("mof_lt_debt_2w_trillion_yen"))
        old_ytd = number(oldv.get("mof_lt_debt_ytd_trillion_yen"))
        new_ytd = number(newv.get("mof_lt_debt_ytd_trillion_yen"))
        if risk_active or sign_bucket(old_2w) != sign_bucket(new_2w) or sign_bucket(old_ytd) != sign_bucket(new_ytd):
            reasons.append("새 일본 재무성 해외중장기채 자금흐름 발표")
        if sign_bucket(old_ytd) != sign_bucket(new_ytd):
            reasons.append("일본 거주자 해외중장기채 연초 이후 누적 방향 전환")

    for key, label in [("auction10", "10년 JGB"), ("auction30", "30년 JGB")]:
        if olds.get(key) and news.get(key) and olds.get(key) != news.get(key):
            reasons.append(f"새 {label} 입찰 결과")
    return reasons


def fmt_flow(value: float) -> str:
    return f"{value:+.2f}조엔"


def build_context(jgb_rows, mof, a10, p10, a30, p30, errors: list[str]) -> str:
    latest_date, jgb10 = jgb_rows[-1]
    days = consecutive_above(jgb_rows, JGB10_BOUNDARY)
    if jgb10 >= JGB10_BOUNDARY:
        jgb_state = f"3% 이상 / 연속 {days}영업일" if days >= 2 else "3% 구조적 경계 위"
    else:
        jgb_state = "3% 구조적 경계 아래"

    lines = [
        "구조적 경계·자금환류",
        f"- 일본 10년 JGB(재무성 공식 종가) {jgb10:.3f}% ({latest_date}) → {jgb_state}",
    ]
    if mof:
        lt_direction = "해외채권 순매수" if mof.latest_2w_lt_debt_trillion_yen > 0 else "해외채권 순매도·환류 압력"
        lines += [
            f"- 해외중장기채: 최근 2주 {fmt_flow(mof.latest_2w_lt_debt_trillion_yen)} / 직전 2주 {fmt_flow(mof.prior_2w_lt_debt_trillion_yen)} / 연초 이후 {fmt_flow(mof.ytd_lt_debt_trillion_yen)} → {lt_direction}",
            f"- 해외주식·투자펀드: 최근 2주 {fmt_flow(mof.latest_2w_equity_trillion_yen)} / 직전 2주 {fmt_flow(mof.prior_2w_equity_trillion_yen)}",
            "※ 해외주식과 해외중장기채를 분리합니다. 엔캐리·글로벌 채권 환류 판단에는 해외중장기채를 우선 봅니다.",
        ]
    else:
        lines.append("- 일본 해외증권투자: 이번 실행 확인 지연")

    lines += ["", "JGB 입찰 수요"]
    if a10:
        prev = f" / 직전 {p10.bid_to_cover:.2f}배·꼬리 {p10.tail_bp:.1f}bp" if p10 else ""
        lines.append(f"- 10년: 입찰배율 {a10.bid_to_cover:.2f}배 / 수익률 꼬리 {a10.tail_bp:.1f}bp{prev} → {auction_label(a10, p10)} ({a10.auction_date})")
    else:
        lines.append("- 10년 JGB 입찰: 이번 실행 확인 지연")
    if a30:
        prev = f" / 직전 {p30.bid_to_cover:.2f}배·꼬리 {p30.tail_bp:.1f}bp" if p30 else ""
        lines.append(f"- 30년: 입찰배율 {a30.bid_to_cover:.2f}배 / 수익률 꼬리 {a30.tail_bp:.1f}bp{prev} → {auction_label(a30, p30)} ({a30.auction_date})")
    else:
        lines.append("- 30년 JGB 입찰: 이번 실행 확인 지연")
    lines += [
        "※ 3% 돌파와 입찰 붕괴를 구분합니다. 높은 금리에서도 입찰이 견조하면 즉시 국채시장 위기로 판정하지 않습니다.",
    ]
    if errors:
        lines += ["", "자료 확인 상태"] + [f"- {e}" for e in errors]
    return "\n".join(lines)


def merge_or_create_alert(context: str, context_payload: dict, reasons: list[str], pending_composite: dict) -> None:
    existing = ALERT_BODY_PATH.exists() and ALERT_JSON_PATH.exists()
    if not existing and not reasons:
        return

    if existing:
        body = ALERT_BODY_PATH.read_text(encoding="utf-8").rstrip()
        if "구조적 경계·자금환류" not in body:
            anchor = "\n\n정확한 의미\n"
            body = body.replace(anchor, "\n\n" + context + anchor) if anchor in body else body + "\n\n" + context
        ALERT_BODY_PATH.write_text(body.rstrip() + "\n", encoding="utf-8")
        payload = load_json(ALERT_JSON_PATH, {})
        payload.setdefault("reasons", [])
        for reason in reasons:
            if reason not in payload["reasons"]:
                payload["reasons"].append(reason)
        payload["structural_context"] = context_payload
        write_json(ALERT_JSON_PATH, payload)
        return

    level = int(pending_composite.get("unwind_level") or 0)
    emoji = {0: "🟢", 1: "🟡", 2: "🟠", 3: "🔴"}.get(level, "🔴")
    title = f"{emoji} 엔캐리 복합 수급 알림"
    body = [
        f"조회 시각: {pending_composite.get('updated_at_kst', '미확인')}",
        "",
        "판정",
        f"- 캐리 청산 위험: {pending_composite.get('unwind_label', '미확인')}",
        f"- 엔화 재약세·캐리 재구축: {pending_composite.get('rebuild_label', '미확인')}",
        "※ 두 판정은 서로 다른 질문이며 동시에 높거나 서로 엇갈릴 수 있습니다.",
        "",
        "이번 변화",
        *[f"- {reason}" for reason in reasons],
        "",
        context,
        "",
        "정확한 의미",
        "- JGB 10년 3%는 엔캐리 자동 청산선이 아니라 구조적·재정적 경계입니다.",
        "- 실제 청산은 일본 단기금리·미일 단기금리차·USD/JPY·FX 변동성·레버리지 포지션을 함께 봅니다.",
        "",
        "출처",
        f"- Japan MOF JGB: {rates.JGB_URL}",
        f"- Japan MOF 해외증권투자: {MOF_WEEK_CSV}",
    ]
    if context_payload.get("auction10"):
        body.append(f"- Japan MOF JGB 10Y auction: {context_payload['auction10']['url']}")
    if context_payload.get("auction30"):
        body.append(f"- Japan MOF JGB 30Y auction: {context_payload['auction30']['url']}")

    ALERT_TITLE_PATH.write_text(title + "\n", encoding="utf-8")
    ALERT_BODY_PATH.write_text("\n".join(body).rstrip() + "\n", encoding="utf-8")
    verdict = {
        "unwind_level": int(pending_composite.get("unwind_level") or 0),
        "unwind_label": pending_composite.get("unwind_label") or "엔캐리 청산 미확인",
        "rebuild_level": int(pending_composite.get("rebuild_level") or 0),
        "rebuild_label": pending_composite.get("rebuild_label") or "엔화 재약세·캐리 재구축 미확인",
        "divergence_short_covering_but_yen_weak": bool(pending_composite.get("divergence_short_covering_but_yen_weak")),
        "evidence": pending_composite.get("evidence") or {},
    }
    write_json(ALERT_JSON_PATH, {"verdict": verdict, "reasons": reasons, "structural_context": context_payload, "errors": []})


def process(now: dt.datetime | None = None) -> int:
    now = (now or dt.datetime.now(UTC)).astimezone(UTC)
    errors: list[str] = []

    try:
        jgb_rows = fetch_jgb10_history()
    except Exception as exc:
        source_failure("Japan MOF JGB 10Y history", rates.JGB_URL, str(exc), now)
        CONTEXT_MD_PATH.write_text("# 엔캐리 구조 보강\n- 상태: JGB 10년 공식자료 확인 실패\n", encoding="utf-8")
        return 0  # optional layer must not block the main composite monitor

    mof = None
    try:
        mof = fetch_mof_split(now)
    except Exception as exc:
        errors.append("일본 재무성 해외증권투자 — 일시적 확인 지연 / 다음 실행 자동 재시도")
        source_failure("Japan MOF ITS split", MOF_WEEK_CSV, str(exc), now)

    a10 = p10 = None
    try:
        a10, p10 = fetch_auction_pair(now, 10)
    except Exception as exc:
        errors.append("10년 JGB 입찰 — 일시적 확인 지연 / 다음 실행 자동 재시도")
        source_failure("Japan MOF 10Y auction", JGB_WHATS_NEW.format(year=now.astimezone(KST).year), str(exc), now)

    a30 = p30 = None
    try:
        a30, p30 = fetch_auction_pair(now, 30)
    except Exception as exc:
        errors.append("30년 JGB 입찰 — 일시적 확인 지연 / 다음 실행 자동 재시도")
        source_failure("Japan MOF 30Y auction", JGB_WHATS_NEW.format(year=now.astimezone(KST).year), str(exc), now)

    pending = make_state(now, jgb_rows, mof, a10, a30)
    previous = load_json(STATE_PATH, {})
    composite = load_json(COMPOSITE_PENDING_PATH, {})
    risk_active = int(composite.get("unwind_level") or 0) > 0 or int(composite.get("rebuild_level") or 0) > 0
    reasons = structural_reasons(previous, pending, risk_active)

    context_payload = {
        "generated_at_kst": now.astimezone(KST).isoformat(timespec="seconds"),
        "jgb10": {"date": jgb_rows[-1][0], "value": jgb_rows[-1][1], "consecutive_days_ge_3": consecutive_above(jgb_rows, JGB10_BOUNDARY)},
        "mof_split": asdict(mof) if mof else None,
        "auction10": asdict(a10) if a10 else None,
        "auction10_previous": asdict(p10) if p10 else None,
        "auction30": asdict(a30) if a30 else None,
        "auction30_previous": asdict(p30) if p30 else None,
        "reasons": reasons,
        "errors": errors,
    }
    context = build_context(jgb_rows, mof, a10, p10, a30, p30, errors)
    write_json(CONTEXT_JSON_PATH, context_payload)
    CONTEXT_MD_PATH.write_text("# 엔캐리 구조 보강\n\n" + context + "\n", encoding="utf-8")
    write_json(PENDING_PATH, pending)
    merge_or_create_alert(context, context_payload, reasons, composite)
    print(json.dumps({"structural_reasons": reasons, "errors": len(errors)}, ensure_ascii=False))
    return 0


def finalize() -> int:
    if not PENDING_PATH.exists():
        return 0
    if ALERT_BODY_PATH.exists():
        confirmation = load_json(CONFIRM_PATH, {})
        if confirmation.get("status") != "confirmed" or confirmation.get("lane") != "yen_carry_composite":
            print("structural state not advanced: Telegram confirmation missing")
            return 1
    pending = load_json(PENDING_PATH, {})
    if not pending:
        return 1
    write_json(STATE_PATH, pending)
    print(f"Finalized yen carry structural state: {STATE_PATH}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--finalize", action="store_true")
    args = parser.parse_args()
    return finalize() if args.finalize else process()


if __name__ == "__main__":
    raise SystemExit(main())
